#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Subprocess Undo helper (#14 Phase 2).

Builds and executes a small Python script that opens a project with
undoable=True, calls project.Undo() (optionally multiple times), and
reports back via JSON-on-stdout.

Separate from handle_run_module's machinery because Undo is a single,
well-defined operation that doesn't need: discovery checks, certification,
mutation validation, operation history, or any of the LLM-facing
guardrails. Reusing run_module would add cost and surface area for no
benefit.
"""

import json
import tempfile
from pathlib import Path
from typing import Dict, Any

try:
    from .subprocess_helpers import run_script_async
except ImportError:
    from server.subprocess_helpers import run_script_async


# Template kept as a single triple-quoted string so it's obvious what runs in
# the subprocess. The {...} placeholders are filled via .format(); inner
# Python braces are doubled to escape them.
_UNDO_SCRIPT_TEMPLATE = '''# Subprocess Undo runner -- generated by handle_undo_last_operation.
import json
import sys
import traceback

PROJECT_NAME = {project_name!r}
UNDO_COUNT = {undo_count}

result = {{"success": False, "undid": 0, "stack_depth_before": None, "stack_depth_after": None}}

try:
    from flexlibs2 import FLExInitialize, FLExCleanup, FLExProject
except Exception as e:
    result["error"] = "import_failed"
    result["error_message"] = "flexlibs2 import failed: {{}}".format(e)
    print("__UNDO_RESULT_START__")
    print(json.dumps(result))
    print("__UNDO_RESULT_END__")
    sys.exit(1)

try:
    FLExInitialize()
except Exception as e:
    result["error"] = "flex_init_failed"
    result["error_message"] = str(e)
    print("__UNDO_RESULT_START__")
    print(json.dumps(result))
    print("__UNDO_RESULT_END__")
    sys.exit(1)

project = None
try:
    project = FLExProject()
    # MUST open with undoable=True for project.Undo() to be available.
    project.OpenProject(projectName=PROJECT_NAME, writeEnabled=True, undoable=True)

    # Best-effort: read undo stack depth before, if LCM exposes it.
    try:
        ah = project.project.ActionHandlerAccessor
        depth_before = getattr(ah, "UndoableActionCount", None)
        if depth_before is not None:
            result["stack_depth_before"] = int(depth_before)
    except Exception:
        pass

    undid = 0
    last_error = None
    for _ in range(max(1, UNDO_COUNT)):
        try:
            ok = project.Undo()
            if ok:
                undid += 1
            else:
                # Undo returned False -> nothing more to undo. Stop trying.
                break
        except Exception as inner:
            last_error = str(inner)
            break

    result["undid"] = undid
    if last_error and undid == 0:
        result["error"] = "undo_failed"
        result["error_message"] = last_error
    else:
        result["success"] = True

    try:
        ah = project.project.ActionHandlerAccessor
        depth_after = getattr(ah, "UndoableActionCount", None)
        if depth_after is not None:
            result["stack_depth_after"] = int(depth_after)
    except Exception:
        pass

except Exception as e:
    result["error"] = "open_or_undo_failed"
    result["error_message"] = str(e)
    result["traceback"] = traceback.format_exc()
finally:
    if project is not None:
        try:
            project.CloseProject()
        except Exception as e:
            result.setdefault("close_warning", str(e))
    try:
        FLExCleanup()
    except Exception:
        pass

# Sentinel-wrapped JSON so the parent can extract reliably even if other
# logging chatter ends up on stdout.
print("__UNDO_RESULT_START__")
print(json.dumps(result))
print("__UNDO_RESULT_END__")
'''


def build_undo_script(project_name: str, undo_count: int = 1) -> str:
    """Render the subprocess Undo script for a given project."""
    return _UNDO_SCRIPT_TEMPLATE.format(
        project_name=project_name,
        undo_count=int(undo_count),
    )


def parse_undo_result(stdout: str) -> Dict[str, Any]:
    """Extract the sentinel-wrapped JSON result from subprocess stdout."""
    start_marker = "__UNDO_RESULT_START__"
    end_marker = "__UNDO_RESULT_END__"
    start = stdout.find(start_marker)
    end = stdout.find(end_marker)
    if start == -1 or end == -1:
        return {
            "success": False,
            "error": "no_result_marker",
            "error_message": "Subprocess did not produce a recognizable result block.",
        }
    payload = stdout[start + len(start_marker):end].strip()
    try:
        return json.loads(payload)
    except json.JSONDecodeError as e:
        return {
            "success": False,
            "error": "result_parse_failed",
            "error_message": str(e),
            "raw": payload[:500],
        }


async def execute_undo(
    project_name: str,
    undo_count: int = 1,
    timeout_seconds: int = 60,
) -> Dict[str, Any]:
    """Run the Undo subprocess and return a structured result.

    Returns a dict with keys:
        success           bool
        undid             int (number of Undo() calls that succeeded)
        stack_depth_before / stack_depth_after  (best-effort; None if unavailable)
        error / error_message  (only on failure)
        subprocess_stderr (subprocess stderr in case of subprocess-level errors)
    """
    script = build_undo_script(project_name, undo_count)
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as fh:
        fh.write(script)
        script_path = fh.name

    try:
        sub_result = await run_script_async(script_path, timeout_seconds=timeout_seconds)
    finally:
        try:
            Path(script_path).unlink()
        except OSError:
            pass

    if sub_result.get("timeout"):
        return {
            "success": False,
            "error": "timeout",
            "error_message": f"Undo subprocess timed out after {timeout_seconds}s.",
        }

    parsed = parse_undo_result(sub_result.get("stdout", ""))
    if not parsed.get("success") and sub_result.get("stderr"):
        parsed["subprocess_stderr"] = sub_result["stderr"][:2000]
    return parsed
